export const langIcons: Record<string, string> = {
  'JavaScript': 'devicon-javascript-plain colored',
  'TypeScript': 'devicon-typescript-plain colored',
  'Python': 'devicon-python-plain colored',
  'Java': 'devicon-java-plain colored',
  'Go': 'devicon-go-original-wordmark colored',
  'Rust': 'devicon-rust-original colored',
  'C++': 'devicon-cplusplus-plain colored',
  'C': 'devicon-c-plain colored',
  'C#': 'devicon-csharp-plain colored',
  'PHP': 'devicon-php-plain colored',
  'Ruby': 'devicon-ruby-plain colored',
  'Swift': 'devicon-swift-plain colored',
  'Kotlin': 'devicon-kotlin-plain colored',
  'Dart': 'devicon-dart-plain colored',
  'HTML': 'devicon-html5-plain colored',
  'CSS': 'devicon-css3-plain colored',
  'SCSS': 'devicon-sass-original colored',
  'Sass': 'devicon-sass-original colored',
  'Less': 'devicon-less-plain-wordmark colored',
  'Vue': 'devicon-vuejs-original colored',
  'Shell': 'devicon-bash-plain colored',
  'Perl': 'devicon-perl-plain colored',
  'Lua': 'devicon-lua-plain colored',
  'R': 'devicon-r-plain colored',
  'MATLAB': 'devicon-matlab-plain colored',
  'Scala': 'devicon-scala-plain colored',
  'Haskell': 'devicon-haskell-plain colored',
  'Clojure': 'devicon-clojure-plain colored',
  'Elixir': 'devicon-elixir-plain colored',
  'Erlang': 'devicon-erlang-plain colored',
  'Julia': 'devicon-julia-plain colored',
  'Groovy': 'devicon-groovy-plain colored',
  'Objective-C': 'devicon-objectivec-plain colored',
  'CoffeeScript': 'devicon-coffeescript-plain colored',
  'Vim script': 'devicon-vim-plain colored',
  'Makefile': 'devicon-make-plain colored',
  'CMake': 'devicon-cmake-plain colored',
  'Dockerfile': 'devicon-docker-plain colored',
  'Jupyter Notebook': 'devicon-jupyter-plain colored',
  'Markdown': 'devicon-markdown-original colored',
  'TeX': 'devicon-latex-original colored',
};

export function getLangIcon(lang: string | null): string {
  if (!lang) return 'devicon-github-original';
  return langIcons[lang] || 'devicon-github-original';
}
